### ISSUE TITLE
Slow mamba install

### ISSUE THREAD

**Issue by adamjamesreid** [cambiotraining/bioinformatics-software-pipelines#11]
mamba install -n phylo iqtree==2.3.3 mafft==7.525

Took a pretty long time to install, may be we could find a less realistic example :-p

**Comment by tavareshugo** [comment]
On the actual course we can cache the packages, so when people do it, it hopefully goes quickly.

For example, if you now do: `mamba create -n metagen2 multiqc bowtie2 metaphlan` it shouldn't take as long (I hope), since the packages will already be present in your first environment.

**Comment by tavareshugo** [comment]
this seems to have worked in the live workshop, by caching the packages ahead of time.
